NetworkOfShops/NetworkOfShops/Controllers/ShopsController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using NetworkOfShops.Models;

namespace NetworkOfShops.Controllers
{
    public class ShopsController : Controller
    {
         private static List<ShopViewModel> shopViewModels = new List<ShopViewModel>(){
                new ShopViewModel { Id = 1, Name = "Biedronka", Email = "b@gmail.com", Street = "Wodna 5", Town = "Warszawa", Telephone = "556778332"},
                new ShopViewModel { Id = 2, Name = "Aldi", Email = "a@gmail.com", Street = "Wodna 25", Town = "Katowice", Telephone = "856778332"},
                new ShopViewModel { Id = 3, Name = "Lidl", Email = "l@gmail.com", Street = "Wodna 35", Town = "Bielsko-Biała", Telephone = "956778332"},
                new ShopViewModel { Id = 4, Name = "Biedronka", Email = "b2@gmail.com", Street = "Wodna 45", Town = "Bielsko-Biała", Telephone = "356778332"},
                new ShopViewModel { Id = 5, Name = "Lidl", Email = "l2@gmail.com", Street = "Wodna 55", Town = "Katowice", Telephone = "256778332"},
                new ShopViewModel { Id = 6, Name = "Aldi", Email = "a2@gmail.com", Street = "Wodna 65", Town = "Cieszyn", Telephone = "776778332"},
                new ShopViewModel { Id = 7, Name = "Kosmos", Email = "k@gmail.com", Street = "Wodna 75", Town = "Cieszyn", Telephone = "886778332"},
                new ShopViewModel { Id = 8, Name = "Biedronka", Email = "b3@gmail.com", Street = "Wodna 85", Town = "Żywiec", Telephone = "353778332"}
        };
        private static ShopItemViewModel shopItemViewModel = new ShopItemViewModel { Shops = shopViewModels };
        // GET: ShopsController
        [ResponseCache(Duration = 120)]
        public ActionResult Index()
        {
            return View(shopItemViewModel);
        }

        // GET: ShopsController/Details/5
        [ResponseCache(Duration = 120, VaryByQueryKeys = new[] { "id" })]
        public ActionResult Details(int id)
        {
            return View(shopItemViewModel.Shops.FirstOrDefault(x=>x.Id == id));
        }
        
    }
}

NetworkOfShops/NetworkOfShops/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NetworkOfShops</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/NetworkOfShops.styles.css" asp-append-version="true" />
</head>
<body class="min-vh-100 d-flex flex-column">
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <div class="container">
            @Html.ActionLink("ATH Shop Network System","Index","Home", null, new { @class= "navbar-brand"})
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
              <ul class="navbar-nav">
                <li class="nav-item">
                  @Html.ActionLink("Strona główna","Index", "Home", null, new { @class= "nav-link"})
                </li>
                <li class="nav-item">
                  @Html.ActionLink("Sklepy","Index","Shops", null, new { @class= "nav-link"})
                </li>
              </ul>
              <div class="ms-lg-auto">
              <partial name="_LoginPartial" />
              </div>
            </div>
          </div>
        </nav>       
    </header>
    <div class="container flex-grow-1 d-flex">
        <main role="main" class="w-100 pb-3">
            @RenderBody()
        </main>
    </div>

    <footer>
        <div class="container d-flex flex-wrap justify-content-center">
            <div class="mw-50">
                <ul class="list-group list-group-flush">
                  <li class="list-group-item">43-309 Bielsko-Biała, ul. Willowa 2</li>
                  <li class="list-group-item">tel. +48 33 8279682, fax: +48 33 8279355</li>
                  <li class="list-group-item">e-mail: biurorektora@ath.bielsko.pl</li>
                </ul>
            </div>
            <div class="mw-50">
                &copy; 2022 - ATH Shop Network System - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @if (IsSectionDefined("Scripts"))
    {
        @await RenderSectionAsync("Scripts", required: true)
    }
</body>
</html>